# Secret-scanner workflow from Arista Networks.
on:
  pull_request:
    types: [synchronize]
  push:
    branches:
      - main
name: Secret Scanner (go/secret-scanner)
jobs:
  scan_secret:
    name: Scan incoming changes
    runs-on: ubuntu-latest
    steps: 
      - name: Run scanner
        uses: aristanetworks/secret-scanner-service-public@main
